In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
import string
import nltk

In [26]:
data = pd.read_csv("mbti_cleaned.csv")

## Feature Extraction using TF-IDF and Count Vectorizer
Here we create the TF-IDF Model in order to extract relevant features from the data and send it to the model for classification

In [27]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

In [28]:
data.dropna(inplace= True)

In [29]:
x_train, x_test, y_train, y_test = train_test_split(data['Posts'],data['type'], random_state=0)
c_v = CountVectorizer() 
x_train.isna().sum()

0

In [30]:
X_train_counts = c_v.fit_transform(x_train)
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)

## Support Vector Machines Model

In [31]:
from sklearn.svm import LinearSVC
clf = LinearSVC().fit(X_train_tfidf, y_train)
y_pred = clf.predict(c_v.transform(x_test))

In [32]:
from sklearn import metrics
print(metrics.classification_report(y_test,y_pred, labels= data.type, target_names=data['type'].unique()))


              precision    recall  f1-score   support

        INFJ       0.54      0.61      0.57       337
        ENTP       0.57      0.37      0.45       151
        INTP       0.65      0.59      0.62       285
        INTJ       0.55      0.52      0.53       230
        ENTJ       0.36      0.38      0.37        53
        INFP       0.55      0.52      0.53       230
        ENFP       0.54      0.61      0.57       337
        ISFP       0.55      0.52      0.53       230
        ENFJ       0.54      0.61      0.57       337
        ISTP       0.65      0.59      0.62       285
        ISFJ       0.54      0.61      0.57       337
        ISTJ       0.54      0.61      0.57       337
        ESTP       0.55      0.52      0.53       230
        ESFP       0.65      0.59      0.62       285
        ESTJ       0.65      0.59      0.62       285
        ESFJ       0.59      0.68      0.63       398

   micro avg       0.57      0.60      0.58   1860762
   macro avg       0.54   

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1537: UserWarning: labels size, 7545, does not match size of target_names, 16
  .format(len(labels), len(target_names))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [37]:
print(metrics.confusion_matrix(y_pred, y_test))

[[  7   1   0   0   0   1   0   0   1   4   0   0   0   0   0   1]
 [  3  68   2  16   0   1   0   1  17  21  11   4   1   2   3   2]
 [  0   2  20  12   0   0   0   2   3   2   4   6   2   2   0   1]
 [  1   4   2  56   0   1   0   1  11   3  10   6   0   1   1   2]
 [  1   1   0   1   4   1   0   0   0   1   0   2   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   1   0   0   0   0]
 [  0   1   1   1   0   0   0   7   0   1   0   0   0   1   0   1]
 [ 14  17   5  14   1   0   0   3 204  60  28  18   4   5   2   1]
 [ 11  25   6  12   2   0   2   2  57 271  16  30   6  11   4   4]
 [  3   9   6  13   1   0   1   0  15   6 119  31   3   2   5   3]
 [  3   5   7  14   1   1   1   2   8  11  21 169   2   4   2  10]
 [  0   1   0   0   0   0   0   0   0   0   1   0  11   0   1   0]
 [  1   3   2   2   0   1   0   0   5   7   4   2   1  15   0   3]
 [  2   2   1   5   0   0   3   1   8   9  10   6   3   0  22 